
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
      - MYSQL_DATABASE=voidpay
      - MYSQL_ROOT_PASSWORD=0000
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

